name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean install -DskipTests

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker image
        run: |
          # Build image with the version of the release
          docker build -t ghcr.io/LeNelSoN/you-are-the-hero:${{ github.event.release.tag_name }} .
          # Tag image as latest
          docker tag ghcr.io/LeNelSoN/you-are-the-hero:${{ github.event.release.tag_name }} ghcr.io/your-github-username/you-are-the-hero:latest

      - name: Push Docker images
        run: |
          # Push the tagged image with the version
          docker push ghcr.io/LeNelSoN/you-are-the-hero:${{ github.event.release.tag_name }}
          # Push the latest tagged image
          docker push ghcr.io/LeNelSoN/you-are-the-hero:latest
